"""
Chemical database for WMD Plotter.
Sources: NIOSH IDLH, AIHA ERPG (2024), US EPA AEGL, DOD TIC list.

ERPG levels (1-hour exposure):
  ERPG-1: Highest concentration below which nearly all individuals could be
           exposed without experiencing transient adverse health effects.
  ERPG-2: Highest concentration below which nearly all individuals could be
           exposed without experiencing irreversible or serious health effects.
  ERPG-3: Highest concentration below which nearly all individuals could be
           exposed without experiencing life-threatening health effects.

AEGL levels (60-minute exposure):
  AEGL-1: Notable discomfort, irritation, or asymptomatic non-sensory effects.
  AEGL-2: Irreversible or other serious, long-lasting adverse health effects.
  AEGL-3: Life-threatening health effects or death.

Units: ppm (v/v) except where noted as mg/m3.
MW: g/mol
Vapor pressure: mmHg at 20°C
Vapor density: relative to air (air = 1.0)
Boiling point: °C
"""

from typing import Optional

CHEMICALS: list[dict] = [
    # ─────────────────────────────────────────────────────────────────────────
    # TOXIC INDUSTRIAL CHEMICALS (TIC)
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "ammonia",
        "name": "Ammonia",
        "formula": "NH₃",
        "cas": "7664-41-7",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 17.03,
        "boiling_point": -33.35,
        "vapor_pressure_20c": 6506,
        "vapor_density": 0.59,
        "physical_state": "gas",
        "idlh_ppm": 300,
        "erpg1_ppm": 25,
        "erpg2_ppm": 150,
        "erpg3_ppm": 750,
        "aegl1_60_ppm": 30,
        "aegl2_60_ppm": 160,
        "aegl3_60_ppm": 1100,
        "description": "Colorless gas with pungent odor. Lighter than air. Widely used in refrigeration and agriculture. BLEVE risk in pressurized storage.",
        "plume_color": "#FFD700",
    },
    {
        "id": "chlorine",
        "name": "Chlorine",
        "formula": "Cl₂",
        "cas": "7782-50-5",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 70.90,
        "boiling_point": -34.05,
        "vapor_pressure_20c": 6800,
        "vapor_density": 2.47,
        "physical_state": "gas",
        "idlh_ppm": 10,
        "erpg1_ppm": 1,
        "erpg2_ppm": 3,
        "erpg3_ppm": 20,
        "aegl1_60_ppm": 0.5,
        "aegl2_60_ppm": 2.0,
        "aegl3_60_ppm": 20.0,
        "description": "Yellow-green gas, heavier than air. Choking/pulmonary agent. Used in water treatment and chemical manufacturing. Dense-gas behavior.",
        "plume_color": "#ADFF2F",
    },
    {
        "id": "hydrogen_sulfide",
        "name": "Hydrogen Sulfide",
        "formula": "H₂S",
        "cas": "7783-06-4",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 34.08,
        "boiling_point": -60.28,
        "vapor_pressure_20c": 15600,
        "vapor_density": 1.19,
        "physical_state": "gas",
        "idlh_ppm": 50,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 30,
        "erpg3_ppm": 100,
        "aegl1_60_ppm": 0.51,
        "aegl2_60_ppm": 27,
        "aegl3_60_ppm": 50,
        "description": "Rotten-egg odor, flammable. Rapidly paralyzes olfactory nerve — smell cannot be relied upon for warning. Causes rapid unconsciousness at high concentrations.",
        "plume_color": "#DAA520",
    },
    {
        "id": "hydrogen_fluoride",
        "name": "Hydrogen Fluoride",
        "formula": "HF",
        "cas": "7664-39-3",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 20.01,
        "boiling_point": 19.5,
        "vapor_pressure_20c": 783,
        "vapor_density": 0.69,
        "physical_state": "gas",
        "idlh_ppm": 30,
        "erpg1_ppm": 2,
        "erpg2_ppm": 20,
        "erpg3_ppm": 50,
        "aegl1_60_ppm": 0.44,
        "aegl2_60_ppm": 22,
        "aegl3_60_ppm": 95,
        "description": "Extremely corrosive. Penetrates skin causing deep tissue and bone damage (hypocalcemia). Boiling point near ambient; dense white fumes in moist air.",
        "plume_color": "#FF6347",
    },
    {
        "id": "hydrogen_cyanide",
        "name": "Hydrogen Cyanide",
        "formula": "HCN",
        "cas": "74-90-8",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 27.03,
        "boiling_point": 25.6,
        "vapor_pressure_20c": 750,
        "vapor_density": 0.94,
        "physical_state": "gas",
        "idlh_ppm": 50,
        "erpg1_ppm": 2.5,
        "erpg2_ppm": 10,
        "erpg3_ppm": 25,
        "aegl1_60_ppm": 2.0,
        "aegl2_60_ppm": 7.1,
        "aegl3_60_ppm": 15,
        "description": "Colorless liquid/gas with bitter almond odor (30% cannot detect). Blood/cellular asphyxiant. Slightly lighter than air. Also military agent AC.",
        "plume_color": "#FF4500",
    },
    {
        "id": "phosgene",
        "name": "Phosgene",
        "formula": "COCl₂",
        "cas": "75-44-5",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 98.92,
        "boiling_point": 7.6,
        "vapor_pressure_20c": 1173,
        "vapor_density": 3.43,
        "physical_state": "gas",
        "idlh_ppm": 2,
        "erpg1_ppm": 0.2,
        "erpg2_ppm": 1.5,
        "erpg3_ppm": 7.5,
        "aegl1_60_ppm": 0.030,
        "aegl2_60_ppm": 0.60,
        "aegl3_60_ppm": 3.6,
        "description": "Colorless gas, faint hay odor. Choking agent (delayed pulmonary edema 4–24h). Very dense. WWI chemical weapon; still produced industrially.",
        "plume_color": "#98FB98",
    },
    {
        "id": "sulfur_dioxide",
        "name": "Sulfur Dioxide",
        "formula": "SO₂",
        "cas": "7446-09-5",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 64.06,
        "boiling_point": -10.0,
        "vapor_pressure_20c": 3300,
        "vapor_density": 2.26,
        "physical_state": "gas",
        "idlh_ppm": 100,
        "erpg1_ppm": 0.3,
        "erpg2_ppm": 3.0,
        "erpg3_ppm": 15,
        "aegl1_60_ppm": 0.20,
        "aegl2_60_ppm": 0.75,
        "aegl3_60_ppm": 9.2,
        "description": "Colorless gas, sharp pungent odor. Heavier than air. Upper respiratory irritant. Used in refrigeration and smelting. Major industrial release hazard.",
        "plume_color": "#FFA500",
    },
    {
        "id": "hydrogen_chloride",
        "name": "Hydrogen Chloride",
        "formula": "HCl",
        "cas": "7647-01-0",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 36.46,
        "boiling_point": -85.05,
        "vapor_pressure_20c": 40800,
        "vapor_density": 1.27,
        "physical_state": "gas",
        "idlh_ppm": 50,
        "erpg1_ppm": 3.0,
        "erpg2_ppm": 20,
        "erpg3_ppm": 150,
        "aegl1_60_ppm": 1.8,
        "aegl2_60_ppm": 22,
        "aegl3_60_ppm": 620,
        "description": "Colorless gas. Forms dense white fumes (hydrochloric acid mist) in moist air. Strong respiratory irritant. Slightly heavier than air.",
        "plume_color": "#20B2AA",
    },
    {
        "id": "carbon_monoxide",
        "name": "Carbon Monoxide",
        "formula": "CO",
        "cas": "630-08-0",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 28.01,
        "boiling_point": -191.5,
        "vapor_pressure_20c": 99999,
        "vapor_density": 0.97,
        "physical_state": "gas",
        "idlh_ppm": 1200,
        "erpg1_ppm": 200,
        "erpg2_ppm": 350,
        "erpg3_ppm": 500,
        "aegl1_60_ppm": 83,
        "aegl2_60_ppm": 420,
        "aegl3_60_ppm": 1700,
        "description": "Odorless, colorless, non-irritating. Binds hemoglobin (230x O2 affinity). No warning properties. Produced by incomplete combustion. Nearly same density as air.",
        "plume_color": "#808080",
    },
    {
        "id": "nitrogen_dioxide",
        "name": "Nitrogen Dioxide",
        "formula": "NO₂",
        "cas": "10102-44-0",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 46.01,
        "boiling_point": 21.2,
        "vapor_pressure_20c": 720,
        "vapor_density": 1.58,
        "physical_state": "gas",
        "idlh_ppm": 20,
        "erpg1_ppm": 1.0,
        "erpg2_ppm": 15,
        "erpg3_ppm": 30,
        "aegl1_60_ppm": 0.50,
        "aegl2_60_ppm": 20,
        "aegl3_60_ppm": 25,
        "description": "Reddish-brown gas. Delayed pulmonary edema. Heavier than air. Produced in acid spills, fertilizer plants, and combustion. Equilibrium with N₂O₄.",
        "plume_color": "#CD853F",
    },
    {
        "id": "methyl_isocyanate",
        "name": "Methyl Isocyanate",
        "formula": "CH₃NCO",
        "cas": "624-83-9",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 57.05,
        "boiling_point": 39.1,
        "vapor_pressure_20c": 348,
        "vapor_density": 1.97,
        "physical_state": "liquid",
        "idlh_ppm": 3,
        "erpg1_ppm": 0.025,
        "erpg2_ppm": 0.5,
        "erpg3_ppm": 5.0,
        "aegl1_60_ppm": 0.013,
        "aegl2_60_ppm": 0.10,
        "aegl3_60_ppm": 1.2,
        "description": "Bhopal disaster agent. Extremely toxic, reacts violently with water to produce CO₂ and heat (runaway reaction risk). Heavier than air. Severe respiratory/eye damage.",
        "plume_color": "#FF0000",
    },
    {
        "id": "acrolein",
        "name": "Acrolein",
        "formula": "C₃H₄O",
        "cas": "107-02-8",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 56.06,
        "boiling_point": 52.5,
        "vapor_pressure_20c": 210,
        "vapor_density": 1.94,
        "physical_state": "liquid",
        "idlh_ppm": 2,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 0.5,
        "erpg3_ppm": 3.0,
        "aegl1_60_ppm": 0.03,
        "aegl2_60_ppm": 0.44,
        "aegl3_60_ppm": 2.5,
        "description": "Extremely toxic. Combustion product of plastics/wood. Very strong lachrymator. Used as biocide/herbicide. Highly flammable.",
        "plume_color": "#FF8C00",
    },
    {
        "id": "acrylonitrile",
        "name": "Acrylonitrile",
        "formula": "C₃H₃N",
        "cas": "107-13-1",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 53.06,
        "boiling_point": 77.3,
        "vapor_pressure_20c": 83,
        "vapor_density": 1.83,
        "physical_state": "liquid",
        "idlh_ppm": 85,
        "erpg1_ppm": 2.5,
        "erpg2_ppm": 35,
        "erpg3_ppm": 75,
        "aegl1_60_ppm": 1.6,
        "aegl2_60_ppm": 29,
        "aegl3_60_ppm": 85,
        "description": "Flammable liquid used in acrylic fiber production. Cyanogens hazard. IARC Group 2B carcinogen. Forms explosive vapors.",
        "plume_color": "#9370DB",
    },
    {
        "id": "arsine",
        "name": "Arsine",
        "formula": "AsH₃",
        "cas": "7784-42-1",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 77.95,
        "boiling_point": -62.5,
        "vapor_pressure_20c": 11000,
        "vapor_density": 2.70,
        "physical_state": "gas",
        "idlh_ppm": 3,
        "erpg1_ppm": 0.005,
        "erpg2_ppm": 0.1,
        "erpg3_ppm": 1.0,
        "aegl1_60_ppm": 0.0050,
        "aegl2_60_ppm": 0.17,
        "aegl3_60_ppm": 0.62,
        "description": "Colorless, garlic-odored gas. Hemolytic agent (destroys red blood cells). Used in semiconductor manufacturing. Very dense, hugs ground.",
        "plume_color": "#7CFC00",
    },
    {
        "id": "phosphine",
        "name": "Phosphine",
        "formula": "PH₃",
        "cas": "7803-51-2",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 33.99,
        "boiling_point": -87.7,
        "vapor_pressure_20c": 35000,
        "vapor_density": 1.17,
        "physical_state": "gas",
        "idlh_ppm": 50,
        "erpg1_ppm": 0.05,
        "erpg2_ppm": 0.5,
        "erpg3_ppm": 5.0,
        "aegl1_60_ppm": 0.030,
        "aegl2_60_ppm": 0.27,
        "aegl3_60_ppm": 1.2,
        "description": "Highly toxic, flammable gas. Used as fumigant and in semiconductor manufacturing. Inhibits cytochrome c oxidase. Garlic/fish odor.",
        "plume_color": "#32CD32",
    },
    {
        "id": "bromine",
        "name": "Bromine",
        "formula": "Br₂",
        "cas": "7726-95-6",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 159.8,
        "boiling_point": 58.8,
        "vapor_pressure_20c": 173,
        "vapor_density": 5.51,
        "physical_state": "liquid",
        "idlh_ppm": 3,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 0.5,
        "erpg3_ppm": 5.0,
        "aegl1_60_ppm": 0.10,
        "aegl2_60_ppm": 0.50,
        "aegl3_60_ppm": 5.0,
        "description": "Reddish-brown fuming liquid. Very dense vapors. Strong oxidizer and corrosive. Severe respiratory and skin damage. Spreads at ground level.",
        "plume_color": "#8B0000",
    },
    {
        "id": "fluorine",
        "name": "Fluorine",
        "formula": "F₂",
        "cas": "7782-41-4",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 38.00,
        "boiling_point": -188.1,
        "vapor_pressure_20c": 99999,
        "vapor_density": 1.31,
        "physical_state": "gas",
        "idlh_ppm": 25,
        "erpg1_ppm": 0.5,
        "erpg2_ppm": 5.0,
        "erpg3_ppm": 20,
        "aegl1_60_ppm": 0.19,
        "aegl2_60_ppm": 1.7,
        "aegl3_60_ppm": 11,
        "description": "Most reactive element. Colorless to pale yellow gas. Reacts violently with virtually all materials. Severe respiratory damage at very low concentrations.",
        "plume_color": "#FFEC8B",
    },
    {
        "id": "chlorine_trifluoride",
        "name": "Chlorine Trifluoride",
        "formula": "ClF₃",
        "cas": "7790-91-2",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 92.45,
        "boiling_point": 11.75,
        "vapor_pressure_20c": 628,
        "vapor_density": 3.19,
        "physical_state": "gas",
        "idlh_ppm": None,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 1.0,
        "erpg3_ppm": 10,
        "aegl1_60_ppm": 0.026,
        "aegl2_60_ppm": 0.54,
        "aegl3_60_ppm": 3.5,
        "description": "Extreme oxidizer — ignites concrete, glass, asbestos on contact. Dense vapor. Used in nuclear fuel processing. Essentially impossible to fight chemically.",
        "plume_color": "#FF69B4",
    },
    {
        "id": "ethylene_oxide",
        "name": "Ethylene Oxide",
        "formula": "C₂H₄O",
        "cas": "75-21-8",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 44.05,
        "boiling_point": 10.7,
        "vapor_pressure_20c": 1460,
        "vapor_density": 1.52,
        "physical_state": "gas",
        "idlh_ppm": 800,
        "erpg1_ppm": 50,
        "erpg2_ppm": 200,
        "erpg3_ppm": 800,
        "aegl1_60_ppm": 8.0,
        "aegl2_60_ppm": 50,
        "aegl3_60_ppm": 390,
        "description": "Flammable, slightly heavier than air. Used in sterilization and chemical manufacturing. IARC Group 1 carcinogen. Wide explosive range (3–100%).",
        "plume_color": "#6495ED",
    },
    {
        "id": "formaldehyde",
        "name": "Formaldehyde",
        "formula": "CH₂O",
        "cas": "50-00-0",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 30.03,
        "boiling_point": -19.0,
        "vapor_pressure_20c": 3850,
        "vapor_density": 1.04,
        "physical_state": "gas",
        "idlh_ppm": 20,
        "erpg1_ppm": 1.0,
        "erpg2_ppm": 10,
        "erpg3_ppm": 25,
        "aegl1_60_ppm": 0.90,
        "aegl2_60_ppm": 14,
        "aegl3_60_ppm": 67,
        "description": "Pungent gas. Carcinogen (IARC Group 1). Severe eye/upper respiratory irritant. Nearly same density as air. Used in resins, textiles, preservatives.",
        "plume_color": "#DEB887",
    },
    {
        "id": "cyanogen_chloride",
        "name": "Cyanogen Chloride",
        "formula": "ClCN",
        "cas": "506-77-4",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 61.47,
        "boiling_point": 12.7,
        "vapor_pressure_20c": 1000,
        "vapor_density": 2.12,
        "physical_state": "gas",
        "idlh_ppm": None,
        "erpg1_ppm": 0.4,
        "erpg2_ppm": 2.0,
        "erpg3_ppm": 10,
        "aegl1_60_ppm": None,
        "aegl2_60_ppm": None,
        "aegl3_60_ppm": None,
        "description": "Military blood agent CK. Colorless gas. Heavier than air. Converts to HCN in body. Lachrymator at low concentrations. Used as tear gas agent.",
        "plume_color": "#DC143C",
    },
    {
        "id": "toluene_diisocyanate",
        "name": "Toluene Diisocyanate (TDI)",
        "formula": "C₉H₆N₂O₂",
        "cas": "584-84-9",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 174.16,
        "boiling_point": 251.0,
        "vapor_pressure_20c": 0.013,
        "vapor_density": 6.0,
        "physical_state": "liquid",
        "idlh_ppm": 2.5,
        "erpg1_ppm": 0.01,
        "erpg2_ppm": 0.1,
        "erpg3_ppm": 1.0,
        "aegl1_60_ppm": 0.002,
        "aegl2_60_ppm": 0.10,
        "aegl3_60_ppm": 0.50,
        "description": "Potent sensitizer and respiratory allergen. Used in polyurethane foam production. Low vapor pressure but extremely toxic. Causes occupational asthma.",
        "plume_color": "#FF1493",
    },
    {
        "id": "methyl_bromide",
        "name": "Methyl Bromide",
        "formula": "CH₃Br",
        "cas": "74-83-9",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 94.94,
        "boiling_point": 3.56,
        "vapor_pressure_20c": 1500,
        "vapor_pressure_20c": 1600,
        "vapor_density": 3.27,
        "physical_state": "gas",
        "idlh_ppm": 250,
        "erpg1_ppm": 25,
        "erpg2_ppm": 200,
        "erpg3_ppm": 850,
        "aegl1_60_ppm": 18,
        "aegl2_60_ppm": 68,
        "aegl3_60_ppm": 310,
        "description": "Colorless odorless gas. Agricultural fumigant. Neurotoxic. Ozone-depleting. Very dense vapors accumulate in low-lying areas. Chloropicrin often added as warning agent.",
        "plume_color": "#556B2F",
    },
    {
        "id": "dimethyl_sulfate",
        "name": "Dimethyl Sulfate",
        "formula": "(CH₃O)₂SO₂",
        "cas": "77-78-1",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 126.13,
        "boiling_point": 188.0,
        "vapor_pressure_20c": 0.7,
        "vapor_density": 4.35,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 1.0,
        "erpg3_ppm": 10,
        "aegl1_60_ppm": None,
        "aegl2_60_ppm": None,
        "aegl3_60_ppm": None,
        "description": "Oily liquid. Strong alkylating agent — carcinogenic, mutagenic. Low odor warning. Delayed symptoms. Very dense vapors. Hydrolyzes to sulfuric acid.",
        "plume_color": "#8B4513",
    },
    {
        "id": "nitrogen_tetroxide",
        "name": "Nitrogen Tetroxide",
        "formula": "N₂O₄",
        "cas": "10544-72-6",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 92.01,
        "boiling_point": 21.15,
        "vapor_pressure_20c": 700,
        "vapor_density": 3.17,
        "physical_state": "liquid",
        "idlh_ppm": 20,
        "erpg1_ppm": 1.0,
        "erpg2_ppm": 15,
        "erpg3_ppm": 30,
        "aegl1_60_ppm": 0.50,
        "aegl2_60_ppm": 20,
        "aegl3_60_ppm": 25,
        "description": "Reddish-brown fuming oxidizer. Rocket propellant (NTO). Dissociates to NO₂ at normal temperatures. Delayed pulmonary edema. Very corrosive, very dense.",
        "plume_color": "#B8860B",
    },
    {
        "id": "chloropicrin",
        "name": "Chloropicrin",
        "formula": "CCl₃NO₂",
        "cas": "76-06-2",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 164.37,
        "boiling_point": 112.4,
        "vapor_pressure_20c": 18.3,
        "vapor_density": 5.67,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 1.0,
        "erpg3_ppm": 3.0,
        "aegl1_60_ppm": None,
        "aegl2_60_ppm": None,
        "aegl3_60_ppm": None,
        "description": "WWI choking/lachrymatory agent (PS). Agricultural fumigant. No odor warning before harmful levels. Vomiting agent at sub-lethal doses. Very dense vapors.",
        "plume_color": "#4682B4",
    },
    {
        "id": "anhydrous_hf",
        "name": "Anhydrous HF (Alkylation Unit)",
        "formula": "HF",
        "cas": "7664-39-3",
        "category": "TIC",
        "subcategory": "Refinery/Petrochemical",
        "mw": 20.01,
        "boiling_point": 19.5,
        "vapor_pressure_20c": 783,
        "vapor_density": 0.69,
        "physical_state": "gas",
        "idlh_ppm": 30,
        "erpg1_ppm": 2.0,
        "erpg2_ppm": 20,
        "erpg3_ppm": 50,
        "aegl1_60_ppm": 0.44,
        "aegl2_60_ppm": 22,
        "aegl3_60_ppm": 95,
        "description": "Used in petroleum alkylation. Aerosol cloud formation — may hug ground despite lower density. Target for CFATS high-risk chemical facilities.",
        "plume_color": "#FF6347",
    },
    {
        "id": "oleum",
        "name": "Oleum (Fuming Sulfuric Acid)",
        "formula": "H₂SO₄·SO₃",
        "cas": "8014-95-7",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 98.08,
        "boiling_point": 337.0,
        "vapor_pressure_20c": 1.0,
        "vapor_density": 3.39,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        "aegl1_60_ppm": 0.10,
        "aegl2_60_ppm": 0.60,
        "aegl3_60_ppm": 12,
        "description": "Generates SO₃ fumes. Extremely corrosive, reacts violently with water. White fuming clouds. Use SO₂/SO₃ thresholds for plume modeling.",
        "plume_color": "#A9A9A9",
    },
    {
        "id": "boron_trifluoride",
        "name": "Boron Trifluoride",
        "formula": "BF₃",
        "cas": "7637-07-2",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 67.81,
        "boiling_point": -99.9,
        "vapor_pressure_20c": 99999,
        "vapor_density": 2.38,
        "physical_state": "gas",
        "idlh_ppm": None,
        "erpg1_ppm": 1.0,
        "erpg2_ppm": 4.0,
        "erpg3_ppm": 20,
        "aegl1_60_ppm": 0.50,
        "aegl2_60_ppm": 4.6,
        "aegl3_60_ppm": 25,
        "description": "Colorless, pungent gas. Fumes in moist air forming HF/H₃BO₃ aerosol. Used as Lewis acid catalyst. Heavier than air. Extremely irritating to lungs.",
        "plume_color": "#20B2AA",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # CHEMICAL WARFARE AGENTS (CWA)
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "sarin",
        "name": "Sarin (GB)",
        "formula": "C₄H₁₀FO₂P",
        "cas": "107-44-8",
        "category": "CWA",
        "subcategory": "Nerve Agent (G-series)",
        "mw": 140.09,
        "boiling_point": 158.0,
        "vapor_pressure_20c": 2.10,
        "vapor_density": 4.86,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # AEGL values from EPA (2003) at 60 min, converted from mg/m³
        # AEGL-2: 0.0035 mg/m³ → ppm = 0.0035 × 1000 / 140.09 × 24.45 = 0.000611
        # AEGL-3: 0.022 mg/m³ → ppm = 0.022 × 1000 / 140.09 × 24.45 = 0.00384
        "aegl1_60_ppm": 0.00017,
        "aegl2_60_ppm": 0.00061,
        "aegl3_60_ppm": 0.0038,
        "description": "NATO designation GB. Organophosphorus nerve agent. Irreversible acetylcholinesterase inhibitor. Colorless liquid with faint fruity odor. Rapid incapacitation. Used in Syrian civil war.",
        "plume_color": "#8B0000",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "soman",
        "name": "Soman (GD)",
        "formula": "C₇H₁₆FO₂P",
        "cas": "96-64-0",
        "category": "CWA",
        "subcategory": "Nerve Agent (G-series)",
        "mw": 182.17,
        "boiling_point": 198.0,
        "vapor_pressure_20c": 0.40,
        "vapor_density": 6.33,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # AEGL-2: 0.0022 mg/m³; AEGL-3: 0.14 mg/m³
        "aegl1_60_ppm": 0.000047,
        "aegl2_60_ppm": 0.00030,
        "aegl3_60_ppm": 0.019,
        "description": "NATO designation GD. Most toxic of G-series. 'Aging' makes antidotes less effective. Camphor-like odor. Lower volatility than GB but very dense.",
        "plume_color": "#A0522D",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "tabun",
        "name": "Tabun (GA)",
        "formula": "C₅H₁₁N₂O₂P",
        "cas": "77-81-6",
        "category": "CWA",
        "subcategory": "Nerve Agent (G-series)",
        "mw": 162.13,
        "boiling_point": 247.5,
        "vapor_pressure_20c": 0.037,
        "vapor_density": 5.63,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # AEGL-2: 0.0078 mg/m³; AEGL-3: 0.048 mg/m³
        "aegl1_60_ppm": 0.00080,
        "aegl2_60_ppm": 0.0012,
        "aegl3_60_ppm": 0.0072,
        "description": "First nerve agent synthesized (Germany, 1936). Faint fruity/almond odor. Lowest volatility of G-series. Stockpiled by several nations. Still a significant threat.",
        "plume_color": "#B22222",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "vx",
        "name": "VX",
        "formula": "C₁₁H₂₆NO₂PS",
        "cas": "50782-69-9",
        "category": "CWA",
        "subcategory": "Nerve Agent (V-series)",
        "mw": 267.37,
        "boiling_point": 298.0,
        "vapor_pressure_20c": 0.0007,
        "vapor_density": 9.2,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # AEGL-2: 0.000096 mg/m³; AEGL-3: 0.00096 mg/m³ (60 min)
        "aegl1_60_ppm": 0.0000018,
        "aegl2_60_ppm": 0.0000088,
        "aegl3_60_ppm": 0.000088,
        "description": "Most toxic nerve agent. Oily, persistent liquid. Very low vapor pressure — mainly a skin/contact hazard, but vapor still hazardous in confined areas or warm weather.",
        "plume_color": "#4B0082",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "novichok",
        "name": "Novichok A-230",
        "formula": "C₅H₁₁FNO₂P",
        "cas": "unknown",
        "category": "CWA",
        "subcategory": "Nerve Agent (Novichok)",
        "mw": 163.12,
        "boiling_point": None,
        "vapor_pressure_20c": None,
        "vapor_density": 5.65,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # Estimated: 5-10x more toxic than VX; very few published data
        "aegl1_60_ppm": 0.0000002,
        "aegl2_60_ppm": 0.0000010,
        "aegl3_60_ppm": 0.0000090,
        "description": "Fourth-generation nerve agent. Estimated 5–10× more toxic than VX. Used in Salisbury (2018) and Navalny (2020) poisonings. Thresholds are engineering estimates only.",
        "plume_color": "#800080",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "mustard_hd",
        "name": "Sulfur Mustard (HD)",
        "formula": "C₄H₈Cl₂S",
        "cas": "505-60-2",
        "category": "CWA",
        "subcategory": "Blister Agent (Vesicant)",
        "mw": 159.07,
        "boiling_point": 217.0,
        "vapor_pressure_20c": 0.072,
        "vapor_density": 5.50,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        # AEGL-2: 0.0028 mg/m³; AEGL-3: 0.050 mg/m³ (60 min)
        "aegl1_60_ppm": 0.00022,
        "aegl2_60_ppm": 0.00043,
        "aegl3_60_ppm": 0.0077,
        "description": "Garlic/mustard odor. Delayed effects (2–24h) — no immediate pain on skin contact. DNA alkylating agent. Carcinogenic. Used in WWI, Iran-Iraq War. Persists in environment.",
        "plume_color": "#8B8B00",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "lewisite",
        "name": "Lewisite (L)",
        "formula": "C₂H₂AsCl₃",
        "cas": "541-25-3",
        "category": "CWA",
        "subcategory": "Blister Agent (Vesicant)",
        "mw": 207.32,
        "boiling_point": 190.0,
        "vapor_pressure_20c": 0.394,
        "vapor_density": 7.2,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        "aegl1_60_ppm": 0.0001,
        "aegl2_60_ppm": 0.0026,
        "aegl3_60_ppm": 0.026,
        "description": "Geranium-like odor. Immediate pain on contact (unlike mustard). Arsenic-based; BAL (British Anti-Lewisite) is antidote. Very dense vapors. Hydrolysis produces toxic arsenical.",
        "plume_color": "#556B2F",
        "warning": "SCHEDULE 1 CWC AGENT — ILLEGAL TO PRODUCE OR STOCKPILE",
    },
    {
        "id": "phosgene_oxime",
        "name": "Phosgene Oxime (CX)",
        "formula": "CCl₂NOH",
        "cas": "1794-86-1",
        "category": "CWA",
        "subcategory": "Blister Agent (Urticant)",
        "mw": 113.94,
        "boiling_point": 129.0,
        "vapor_pressure_20c": 11.2,
        "vapor_density": 3.9,
        "physical_state": "solid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        "aegl1_60_ppm": 0.00010,
        "aegl2_60_ppm": 0.0010,
        "aegl3_60_ppm": 0.010,
        "description": "Not a true vesicant — nettle/urticant agent causing immediate intense pain. Penetrates protective equipment rapidly. Solid at room temp; 'snow' dispersal. Very rare.",
        "plume_color": "#DDA0DD",
        "warning": "SCHEDULE 1 CWC AGENT",
    },
    {
        "id": "hydrogen_cyanide_ac",
        "name": "Hydrogen Cyanide (AC)",
        "formula": "HCN",
        "cas": "74-90-8",
        "category": "CWA",
        "subcategory": "Blood Agent",
        "mw": 27.03,
        "boiling_point": 25.6,
        "vapor_pressure_20c": 750,
        "vapor_density": 0.94,
        "physical_state": "gas",
        "idlh_ppm": 50,
        "erpg1_ppm": 2.5,
        "erpg2_ppm": 10,
        "erpg3_ppm": 25,
        "aegl1_60_ppm": 2.0,
        "aegl2_60_ppm": 7.1,
        "aegl3_60_ppm": 15,
        "description": "Military designation AC. Blood/cellular asphyxiant. Slightly lighter than air. Poor persistence. Bitter almond odor — 30% cannot smell it. High concentrations cause rapid death.",
        "plume_color": "#FF4500",
        "warning": "SCHEDULE 3 CWC AGENT",
    },
    {
        "id": "diphosgene",
        "name": "Diphosgene (DP)",
        "formula": "Cl₃COCOCl",
        "cas": "503-38-8",
        "category": "CWA",
        "subcategory": "Choking Agent",
        "mw": 197.83,
        "boiling_point": 127.0,
        "vapor_pressure_20c": 10,
        "vapor_density": 6.9,
        "physical_state": "liquid",
        "idlh_ppm": None,
        "erpg1_ppm": 0.1,
        "erpg2_ppm": 0.6,
        "erpg3_ppm": 2.0,
        "aegl1_60_ppm": 0.030,
        "aegl2_60_ppm": 0.60,
        "aegl3_60_ppm": 3.6,
        "description": "Trichloromethyl chloroformate. Hydrolyzes to phosgene (CG). WWI choking agent. Dense liquid, very dense vapors. Use phosgene AEGL values for planning.",
        "plume_color": "#228B22",
        "warning": "SCHEDULE 3 CWC AGENT",
    },
    {
        "id": "chlorine_cwa",
        "name": "Chlorine (CL)",
        "formula": "Cl₂",
        "cas": "7782-50-5",
        "category": "CWA",
        "subcategory": "Choking Agent",
        "mw": 70.90,
        "boiling_point": -34.05,
        "vapor_pressure_20c": 6800,
        "vapor_density": 2.47,
        "physical_state": "gas",
        "idlh_ppm": 10,
        "erpg1_ppm": 1,
        "erpg2_ppm": 3,
        "erpg3_ppm": 20,
        "aegl1_60_ppm": 0.5,
        "aegl2_60_ppm": 2.0,
        "aegl3_60_ppm": 20.0,
        "description": "First mass-use chemical weapon (Ypres, 1915). Yellow-green, visible cloud. Pulmonary edema. Dense vapors fill trenches/low areas. Still used by non-state actors (ISIS, Syria).",
        "plume_color": "#ADFF2F",
        "warning": "SCHEDULE 3 CWC AGENT (dual-use)",
    },
    {
        "id": "adamsite",
        "name": "Adamsite (DM)",
        "formula": "C₁₂H₉AsClNO",
        "cas": "578-94-9",
        "category": "CWA",
        "subcategory": "Vomiting Agent",
        "mw": 277.58,
        "boiling_point": 410.0,
        "vapor_pressure_20c": 0.0002,
        "vapor_density": 9.6,
        "physical_state": "solid",
        "idlh_ppm": None,
        "erpg1_ppm": None,
        "erpg2_ppm": None,
        "erpg3_ppm": None,
        "aegl1_60_ppm": 0.0001,
        "aegl2_60_ppm": 0.0010,
        "aegl3_60_ppm": 0.010,
        "description": "Diphenylaminochloroarsine. Vomiting/sneezing agent. Dispersed as smoke/aerosol. Solid at room temp. Causes severe nausea, vomiting, and headache. Used for crowd control.",
        "plume_color": "#708090",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # ADDITIONAL TICs
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "anhydrous_ammonia_liquid",
        "name": "Liquid Ammonia (Rail/Storage)",
        "formula": "NH₃",
        "cas": "7664-41-7",
        "category": "TIC",
        "subcategory": "Refrigerant/Agricultural",
        "mw": 17.03,
        "boiling_point": -33.35,
        "vapor_pressure_20c": 6506,
        "vapor_density": 0.59,
        "physical_state": "liquid",
        "idlh_ppm": 300,
        "erpg1_ppm": 25,
        "erpg2_ppm": 150,
        "erpg3_ppm": 750,
        "aegl1_60_ppm": 30,
        "aegl2_60_ppm": 160,
        "aegl3_60_ppm": 1100,
        "description": "Large-scale ammonia transport/storage. Flash evaporation on release forms two-phase aerosol cloud. Initial cloud may behave as dense gas before aerosol evaporates. Major CAMEO scenario.",
        "plume_color": "#FFD700",
    },
    {
        "id": "carbon_disulfide",
        "name": "Carbon Disulfide",
        "formula": "CS₂",
        "cas": "75-15-0",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 76.14,
        "boiling_point": 46.2,
        "vapor_pressure_20c": 297,
        "vapor_density": 2.63,
        "physical_state": "liquid",
        "idlh_ppm": 500,
        "erpg1_ppm": 1.0,
        "erpg2_ppm": 50,
        "erpg3_ppm": 500,
        "aegl1_60_ppm": 13,
        "aegl2_60_ppm": 50,
        "aegl3_60_ppm": 500,
        "description": "Highly flammable (flash point -30°C). Neurotoxin. Used in rayon/rubber production. Very low ignition temperature (100°C). Dense vapors.",
        "plume_color": "#DAA520",
    },
    {
        "id": "methyl_mercaptan",
        "name": "Methyl Mercaptan",
        "formula": "CH₃SH",
        "cas": "74-93-1",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 48.11,
        "boiling_point": 5.95,
        "vapor_pressure_20c": 1620,
        "vapor_density": 1.66,
        "physical_state": "gas",
        "idlh_ppm": 150,
        "erpg1_ppm": 0.005,
        "erpg2_ppm": 25,
        "erpg3_ppm": 100,
        "aegl1_60_ppm": 0.0020,
        "aegl2_60_ppm": 17,
        "aegl3_60_ppm": 68,
        "description": "Skunk-like odor at ppb levels. Added to natural gas as odorant. Texas City 1987 — large rail car release. Flammable and toxic at higher concentrations.",
        "plume_color": "#9ACD32",
    },
    {
        "id": "allyl_chloride",
        "name": "Allyl Chloride",
        "formula": "C₃H₅Cl",
        "cas": "107-05-1",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 76.53,
        "boiling_point": 44.5,
        "vapor_pressure_20c": 295,
        "vapor_density": 2.64,
        "physical_state": "liquid",
        "idlh_ppm": 300,
        "erpg1_ppm": 3.0,
        "erpg2_ppm": 40,
        "erpg3_ppm": 300,
        "aegl1_60_ppm": 2.0,
        "aegl2_60_ppm": 22,
        "aegl3_60_ppm": 120,
        "description": "Pungent, lachrymatory. Used in epichlorohydrin production. Flammable. Liver and kidney toxin. Dense vapors.",
        "plume_color": "#6B8E23",
    },
    {
        "id": "butadiene",
        "name": "1,3-Butadiene",
        "formula": "C₄H₆",
        "cas": "106-99-0",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 54.09,
        "boiling_point": -4.41,
        "vapor_pressure_20c": 2400,
        "vapor_density": 1.87,
        "physical_state": "gas",
        "idlh_ppm": 2000,
        "erpg1_ppm": 10,
        "erpg2_ppm": 50,
        "erpg3_ppm": 5000,
        "aegl1_60_ppm": 21,
        "aegl2_60_ppm": 1700,
        "aegl3_60_ppm": 5000,
        "description": "Primarily a fire/explosion hazard. IARC Group 1 carcinogen. Wide flammable range (2–12%). Used in synthetic rubber production. Dense vapors.",
        "plume_color": "#B0C4DE",
    },
    {
        "id": "vinyl_chloride",
        "name": "Vinyl Chloride",
        "formula": "C₂H₃Cl",
        "cas": "75-01-4",
        "category": "TIC",
        "subcategory": "Industrial Gas",
        "mw": 62.50,
        "boiling_point": -13.4,
        "vapor_pressure_20c": 2580,
        "vapor_density": 2.15,
        "physical_state": "gas",
        "idlh_ppm": None,
        "erpg1_ppm": 500,
        "erpg2_ppm": 5000,
        "erpg3_ppm": 20000,
        "aegl1_60_ppm": 82,
        "aegl2_60_ppm": 4900,
        "aegl3_60_ppm": 22000,
        "description": "East Palestine, OH (2023). IARC Group 1 carcinogen (angiosarcoma). Explosion/fire hazard primary concern in incidents. Dense vapors. PVC precursor.",
        "plume_color": "#87CEEB",
    },
    {
        "id": "styrene",
        "name": "Styrene",
        "formula": "C₈H₈",
        "cas": "100-42-5",
        "category": "TIC",
        "subcategory": "Industrial Liquid",
        "mw": 104.15,
        "boiling_point": 145.2,
        "vapor_pressure_20c": 5.0,
        "vapor_density": 3.60,
        "physical_state": "liquid",
        "idlh_ppm": 700,
        "erpg1_ppm": 50,
        "erpg2_ppm": 250,
        "erpg3_ppm": 1000,
        "aegl1_60_ppm": 6.0,
        "aegl2_60_ppm": 170,
        "aegl3_60_ppm": 850,
        "description": "Sweet odor. Polystyrene precursor. Vishakhapatnam chemical plant disaster (2020) involved styrene release. Dense vapors. CNS depressant at high levels.",
        "plume_color": "#F0E68C",
    },
]


def get_chemical(chem_id: str) -> dict | None:
    """Return chemical dict by ID, or None if not found."""
    for c in CHEMICALS:
        if c["id"] == chem_id:
            return c
    return None


def get_chemicals_by_category(category: str) -> list[dict]:
    """Return all chemicals in a given category ('TIC' or 'CWA')."""
    return [c for c in CHEMICALS if c["category"] == category]


def get_thresholds(chem: dict, use_aegl: bool = True) -> dict:
    """
    Return the three concentration thresholds (low/medium/high) for a chemical.
    Prefers AEGL-60min if use_aegl=True and data available; falls back to ERPG.
    Returns concentrations in ppm.
    """
    if use_aegl and chem.get("aegl1_60_ppm") and chem.get("aegl2_60_ppm") and chem.get("aegl3_60_ppm"):
        return {
            "low": {"value": chem["aegl1_60_ppm"], "label": "AEGL-1 (60min)", "color": "#FFFF00"},
            "medium": {"value": chem["aegl2_60_ppm"], "label": "AEGL-2 (60min)", "color": "#FF8C00"},
            "high": {"value": chem["aegl3_60_ppm"], "label": "AEGL-3 (60min)", "color": "#FF0000"},
        }
    elif chem.get("erpg1_ppm") and chem.get("erpg2_ppm") and chem.get("erpg3_ppm"):
        return {
            "low": {"value": chem["erpg1_ppm"], "label": "ERPG-1", "color": "#FFFF00"},
            "medium": {"value": chem["erpg2_ppm"], "label": "ERPG-2", "color": "#FF8C00"},
            "high": {"value": chem["erpg3_ppm"], "label": "ERPG-3", "color": "#FF0000"},
        }
    else:
        # Partial data — use what's available, estimate missing
        idlh = chem.get("idlh_ppm")
        if idlh:
            return {
                "low": {"value": idlh * 0.1, "label": "0.1× IDLH (est.)", "color": "#FFFF00"},
                "medium": {"value": idlh * 0.3, "label": "0.3× IDLH (est.)", "color": "#FF8C00"},
                "high": {"value": idlh, "label": "IDLH", "color": "#FF0000"},
            }
    return {}
